<?php
$create_table = "CREATE TABLE IF NOT EXISTS `{$table}` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `make` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    `model` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    `additional` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `slug` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `salePrice` decimal(20,2) DEFAULT 0.00,
    `msrp` decimal(20,2) DEFAULT 0.00,
    `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
    `addtionalInfo` text COLLATE utf8_unicode_ci DEFAULT NULL,
    `vehicleCondition` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `payloadCapacity` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `emptyWeight` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `floorLength` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `floorWidth` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `sideHeight` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `bodyType` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `featuredImage` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `gallery` text COLLATE utf8_unicode_ci DEFAULT NULL,
    `featuredid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `galleryfiles` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `status` int(11) DEFAULT 0,
    `createdBy` int(11) DEFAULT 0,
    `createdAt` datetime DEFAULT current_timestamp(),
    `updatedBy` int(11) DEFAULT 0,
    `updatedAt` datetime DEFAULT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;";